// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2XfU4luwhkTTtci5rDAXF-eV9WHkr3o',
    appId: '1:213655786767:web:88e7e40faeba07be73da7a',
    messagingSenderId: '213655786767',
    projectId: 'spend-wise-465a0',
    authDomain: 'spend-wise-465a0.firebaseapp.com',
    storageBucket: 'spend-wise-465a0.firebasestorage.app',
    measurementId: 'G-KCZZ9NCES3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOs9obKdZksGWF9WSkYWJ79MzFxswyww',
    appId: '1:213655786767:android:d4f509f5e40254bc73da7a',
    messagingSenderId: '213655786767',
    projectId: 'spend-wise-465a0',
    storageBucket: 'spend-wise-465a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-QdEdu06MVe3bPX_26a0jwQxwJ9Wmy4',
    appId: '1:213655786767:ios:8a773930f4a23a8e73da7a',
    messagingSenderId: '213655786767',
    projectId: 'spend-wise-465a0',
    storageBucket: 'spend-wise-465a0.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn2XfU4luwhkTTtci5rDAXF-eV9WHkr3o',
    appId: '1:213655786767:web:5ea61a54e34b7c9073da7a',
    messagingSenderId: '213655786767',
    projectId: 'spend-wise-465a0',
    authDomain: 'spend-wise-465a0.firebaseapp.com',
    storageBucket: 'spend-wise-465a0.firebasestorage.app',
    measurementId: 'G-ZPEG8TPV1W',
  );
}
